name: Testing

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - dev

  workflow_dispatch:

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run Tests
        run: ./gradlew test

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: Test-Reports
          path: rupiahedittext/build/reports
        if: always()

  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: setup version tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: dekzitfz/RupiahEditText
          releases-only: false
        id: versiontag
      - run: echo "versiontag is at ${{ steps.versiontag.outputs.tag }}"

      - name: checkout repo
        uses: actions/checkout@v3

      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: ${{ steps.versiontag.outputs.tag }}