name: CI/CD
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  step-1:
    name: Step 1
    uses: ./.github/workflows/test.yml

  step-2:
    needs: step-1
    name: Step 2
    uses: ./.github/workflows/build.yml

  step-3:
    needs: step-2
    name: Step 3
    uses: ./.github/workflows/release.yml